- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/exp55/target/exp5.war"
        dest: "/opt/tomcat/webapps/"
        remote_src: no
