- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy to Tomcat
      src: "/var/lib/jenkins/workspace/exp55/target/Maven-AnsibleWebApp.war"
      dest: "/opt/tomcat/webapps/"
      remote_src: no
